#!/bin/python3

height = input("enter your height in m: ")
weight = input("enter your weight in kg: ")

height_user = float(height) * float(height)
weight_user = int(weight)
BMI= int(weight_user / height_user)

print(BMI)


############################## BMI version 2


height = float(input("enter your height in m: "))
weight = float(input("enter your weight in kg: "))

height_user = (height * height)

bmi = int(round((weight / height_user),0))

if bmi < 18.5:
    print (f"Your BMI is {bmi}, you are slightly underweight.")
elif bmi < 25:
    print (f"Your BMI is {bmi}, you have a normal weight.")
elif bmi < 30:
    print (f"Your BMI is {bmi}, you are slightly overweight.")
elif bmi < 35:
    print (f"Your BMI is {bmi}, you are obese.")
else:
     print (f"Your BMI is {bmi}, you are clinically obese.")  
