#!/bin/python3

import random

rock = '''
    _______
---'   ____)
      (_____)
      (_____)
      (____)
---.__(___)
'''

paper = '''
    _______
---'   ____)____
          ______)
          _______)
         _______)
---.__________)
'''

scissors = '''
    _______
---'   ____)____
          ______)
       __________)
      (____)
---.__(___)
'''

list_choice = [rock, paper, scissors]

user_choose = input("What do you choose? Type 0 for Rock, 1 for Paper or 2 for Scissors.\n")
print(list_choice[user_choose])

##need to finish

random_choice_bot = random.choice(list_choice)
