#!/bin/python3

print("Welcome to the tip calculator!")
bill = input("What was the total bill? $")
tip = input("How much tip would you like to give? 10, 12, or 15? ")
people = input("How many people to split the bill? ")

total = round((float(bill) +(float(bill) * (1 + int(tip)/100)) / int(people),2)
