#!/bin/python3

print("Welcome to the tip calculator!")
bill = input("What was the total bill? $")
tip = input("How much tip would you like to give? 10, 12, or 15? ")
people = input("How many people to split the bill? ")

total_tip = 1 + (int(tip)/100)
total_bill_tip= float(bill) * total_tip
total_bill_tip_people= round((total_bill_tip / int(people)),2)

print(f"Each person should pay: ${total_bill_tip_people}")
