#!/bin/python3

print ("Welcome to Treasure Island. Your mission is to find the treasure.")

left_or_right = input('You are at a crossroad. Where do you want to go? Type "left" or "right"\n')

if left_or_right == "left":
  swim_wait = input('You have come to a lake. There is an island in the middle of the lake. Type "wait" to wait for a boat. Type "swim" to swim across.\n')
  if swim_wait == "wait":
    door = input("You arrive at the island unharmed. There is a house with 3 doors. One RED, one YELLOW and one BLUE. Which colour do you choose?\n")
    if door == "RED":
      print("It's a room full of fire. Game Over.")
    elif door == "BLUE":
      print("You enter a room of beasts. Game Over.")
    elif door == "YELLOW":
      print("You found the treasure! You Win!")
    else:
      print("Game Over")
else:
  print("You fell into a hole. Game Over.")
