#!/bin/python3


row1 = ["⬜️","️⬜️","️⬜️"]
row2 = ["⬜️","⬜️","️⬜️"]
row3 = ["⬜️️","⬜️️","⬜️️"]
map = [row1, row2, row3]
print(f"{row1}\n{row2}\n{row3}")
position = input("Where do you want to put the treasure? ")


#Get first number in position
horizontal = int(position[0])

#Get second number in position
vertical = int(position[1])

mark_horizontal = map[vertical -1]
mark_horizontal[horizontal -1] = "X"


print(f"{row1}\n{row2}\n{row3}")
